#!/bin/bash

#module purge
module load PrgEnv-gnu/8.3.3
module load amd-mixed
module load cray-python
module load rocm
module load craype-accel-amd-gfx90a
module load cray-libsci
module load gdb4hpc

export WRAP=WRAP
export TOOLKIT=GNU
export MPILIB=MPICH
export PATH_MPICH=${CRAY_MPICH_PREFIX}
export BUILD_TYPE=OPT
export BLASLIB=LIBSCI
export EXA_OS=LINUX
export PATH_BLAS_LIBSCI=${CRAY_LIBSCI_PREFIX_DIR}/lib
export GPU_CUDA=CUDA
export GPU_SM_ARCH=90
export USE_HIP=YES
export PATH_ROCM=${ROCM_PATH}

#missing linking?
#-I${MPICH_DIR}/include
#-L${MPICH_DIR}/lib -lmpi \
#  ${CRAY_XPMEM_POST_LINK_OPTS} -lxpmem \
#  ${PE_MPICH_GTL_DIR_amd_gfx90a} ${PE_MPICH_GTL_LIBS_amd_gfx90a}



#additional env
export HIPFLAGS='--amdgpu-target=gfx90a'
export CXX='CC –x hip'
export LDFLAGS=" –L${ROCM_PATH}/lib"
export LIB=' -lamdhip64'


