#!/bin/bash

module purge
module load DefApps/default
module load libfabric
module load PrgEnv-gnu
module load amd-mixed
module load cray-mpich
module load cray-libsci
module load cray-libsci_acc
module load cray-python
module load craype-network-ofi
module load cray-hdf5-parallel
module load craype-x86-trento
module load rocm
module load craype-accel-amd-gfx90a
module load craype-hugepages2M
module load gdb4hpc
module load darshan-runtime
module load perftools-base
module load xpmem
module load cray-pmi

export WRAP=WRAP
export TOOLKIT=GNU
export MPILIB=MPICH
export PATH_MPICH=${CRAY_MPICH_PREFIX}
export BUILD_TYPE=OPT
export BLASLIB=LIBSCI
export EXA_OS=LINUX
export PATH_BLAS_LIBSCI=${CRAY_LIBSCI_PREFIX_DIR}/lib
export WITH_LAPACK=NO
export GPU_CUDA=CUDA
export GPU_SM_ARCH=90
export USE_HIP=YES
export PATH_ROCM=${ROCM_PATH}

#missing linking?
#-I${MPICH_DIR}/include
#-L${MPICH_DIR}/lib -lmpi \
#  ${CRAY_XPMEM_POST_LINK_OPTS} -lxpmem \
#  ${PE_MPICH_GTL_DIR_amd_gfx90a} ${PE_MPICH_GTL_LIBS_amd_gfx90a}



#additional env
export HIPFLAGS='--amdgpu-target=gfx90a'
export CXX='CC –x hip'
export LDFLAGS=" –L${ROCM_PATH}/lib"
export LIB=' -lamdhip64'


